import os
from typing import List

from util.datasets import PhpDataset
from model import *

import numpy as np
from torch.utils.data import DataLoader
from sklearn import metrics

import torch
from collections import OrderedDict

# those paths containing json datas generated by preprocess module
train_path = 'phpProcessor/files/sequence/train/'
test_path = 'phpProcessor/files/sequence/test/'

def label_smoothing(inputs, epsilon=0.1):
    '''Applies label smoothing. See 5.4 and https://arxiv.org/abs/1512.00567.
    inputs: 3d tensor. [N, T, V], where V is the number of vocabulary.
    epsilon: Smoothing rate.
    For example,
    ```
    import tensorflow as tf
    inputs = tf.convert_to_tensor([[[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]],
      [[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]]], tf.float32)
    outputs = label_smoothing(inputs)
    with tf.Session() as sess:
        print(sess.run([outputs]))
    >>
    [array([[[ 0.03333334,  0.03333334,  0.93333334],
        [ 0.03333334,  0.93333334,  0.03333334],
        [ 0.93333334,  0.03333334,  0.03333334]],
       [[ 0.93333334,  0.03333334,  0.03333334],
        [ 0.93333334,  0.03333334,  0.03333334],
        [ 0.03333334,  0.93333334,  0.03333334]]], dtype=float32)]
    ```
    '''
    # V = inputs.size().as_list()[-1]  # number of channels
    return ((1 - epsilon) * inputs) + (epsilon / 2)


def loss_fn(outputs, targets):
    return torch.nn.BCEWithLogitsLoss()(outputs, targets)


def train(epoch, training_loader, model):
    model.train()
    if not os.path.exists('./model'):
        os.makedirs('./model')  # 创建保存模型的目录

    for i in range(epoch):
        total_loss = 0
        total_correct = 0
        num_samples = 0

        for _, data in enumerate(training_loader, 0):
            targets = data['targets'].view(-1, 1).to(conf.device, dtype=torch.float).cuda(
                non_blocking=True)  # [batch_size, 1]
            ids = data['ids'].to(conf.device, dtype=torch.long).cuda(non_blocking=True)
            mask = data['mask'].to(conf.device, dtype=torch.long).cuda(non_blocking=True)
            token_type_ids = data['token_type_ids'].to(conf.device, dtype=torch.long).cuda(non_blocking=True)

            if hasattr(torch.cuda, 'empty_cache'):
                torch.cuda.empty_cache()

            outputs = model(ids, mask, token_type_ids)  # 输出 [batch_size, 1] logits
            loss = loss_fn(outputs, targets)

            pred_choice = (outputs > 0).float()  # logits > 0 等价于 sigmoid > 0.5
            correct = pred_choice.eq(targets).cpu().sum()
            total_correct += correct.item()
            total_loss += loss.item()
            num_samples += conf.batch_size  # 假设 conf.batch_size 已定义

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if hasattr(torch.cuda, 'empty_cache'):
                torch.cuda.empty_cache()

            print('[%d: %d/%d] train loss: %f accuracy: %f' % (
                i, _, len(training_loader), loss.item(), correct.item() / float(conf.batch_size)))

        # 每轮次结束后保存模型
        avg_loss = total_loss / len(training_loader)
        avg_acc = total_correct / num_samples
        print(f'Epoch [{i + 1}/{epoch}] completed. Avg Loss: {avg_loss:.4f}, Avg Accuracy: {avg_acc:.4f}')

        # 保存模型
        save_path = os.path.join('./model/', f'cls_model_epoch_{i + 1}.pth')
        torch.save(model.state_dict(), save_path)
        print(f'Model saved to {save_path}')

# def train(epoch, training_loader, model):
#     model.train()
#     for i in range(epoch):
#         for _, data in enumerate(training_loader, 0):
#             targets = data['targets']
#             targets = targets.view(-1, 1)
#             targets = torch.LongTensor(targets)
#             targets = torch.zeros(targets.shape[0], 2).scatter_(1, targets, 1)
#
#             ids = data['ids'].to(conf.device, dtype=torch.long).cuda(non_blocking=True)
#             mask = data['mask'].to(conf.device, dtype=torch.long).cuda(non_blocking=True)
#             token_type_ids = data['token_type_ids'].to(conf.device, dtype=torch.long).cuda(non_blocking=True)
#             targets = targets.to(conf.device, dtype=torch.float).cuda(non_blocking=True)
#             targets = label_smoothing(targets)
#             # print(targets)
#             if hasattr(torch.cuda, 'empty_cache'):
#                 torch.cuda.empty_cache()
#
#             outputs = model(ids, mask, token_type_ids)
#
#             if hasattr(torch.cuda, 'empty_cache'):
#                 torch.cuda.empty_cache()
#             optimizer.zero_grad()
#             # print(outputs)
#             loss = loss_fn(outputs, targets)
#
#             pred_choice = outputs.max(1)[1]
#             targets = targets.max(1)[1]
#             # print(pred_choice, targets)
#             correct = pred_choice.eq(targets).cpu().sum()
#             print('[%d: %d/%d] train loss: %f accuracy: %f' % (
#             i, _, num_batch, loss.item(), correct.item() / float(conf.batch_size)))
#
#
#             loss.backward()
#             optimizer.step()
#             #scheduler.step()
#             #torch.save(model.module.state_dict(), '%s/cls_model_%d.pth' % ('model', epoch))

def validation(testing_loader, model):
    model.eval()

    outs = []
    tars = []

    with torch.no_grad():
        for _, data in enumerate(testing_loader, 0):
            targets = data['targets']
            targets = targets.view(-1, 1)
            targets = torch.LongTensor(targets)
            targets = torch.zeros(targets.shape[0], 2).scatter_(1, targets, 1)

            ids = data['ids'].to(conf.device, dtype=torch.long)
            mask = data['mask'].to(conf.device, dtype=torch.long)
            token_type_ids = data['token_type_ids'].to(conf.device, dtype=torch.long)
            targets = targets.to(conf.device, dtype=torch.float)

            outputs = model(ids, mask, token_type_ids)
            outputs = outputs.max(1)[1]
            targets = targets.max(1)[1]

            outs.append(outputs.cpu())
            tars.append(targets.cpu())

    output = torch.cat(outs, 0)
    target = torch.cat(tars, 0).numpy()
    output = np.array(output) >= 0.5

    print(metrics.confusion_matrix(target, output))
    print(metrics.accuracy_score(target, output))
    print(metrics.f1_score(target, output))
    print(metrics.recall_score(target, output))
    print(metrics.precision_score(target, output))


def load_pretrained_model(
        model: torch.nn.Module,
        checkpoint_path: str,
        exclude_layers: List[str] = None
) -> torch.nn.Module:
    """
    加载预训练模型的权重，并排除指定层的权重。

    参数:
        model (torch.nn.Module): 需要加载权重的模型实例。
        checkpoint_path (str): 预训练模型权重的路径。
        exclude_layers (List[str]): 需要排除的层名称（默认为空）。

    返回:
        torch.nn.Module: 加载了预训练权重的模型。
    """
    # 加载预训练模型的 checkpoint
    checkpoint = torch.load(checkpoint_path, map_location=conf.device)

    # 如果 checkpoint 是一个完整的训练状态，提取 model_state_dict
    if 'model_state_dict' in checkpoint:
        checkpoint = checkpoint['model_state_dict']

    # 如果未指定排除层，则默认为空列表
    if exclude_layers is None:
        exclude_layers = []

    # 过滤掉需要排除的层
    pretrained_params = {
        k: v for k, v in checkpoint.items()
        if not any(exclude in k for exclude in exclude_layers)
    }

    # 获取当前模型的状态字典
    model_state_dict = model.state_dict()

    # 更新当前模型的状态字典
    model_state_dict.update(pretrained_params)

    # 加载更新后的状态字典
    model.load_state_dict(model_state_dict)

    # print(f"Loaded pretrained weights from {checkpoint_path}, excluding layers: {exclude_layers}")
    return model

if __name__ == '__main__':
    train_dataset = PhpDataset(train_path)
    test_dataset = PhpDataset(test_path)

    training_loader = DataLoader(dataset=train_dataset, batch_size=conf.batch_size, shuffle=True, num_workers=2, drop_last=False)
    testing_loader = DataLoader(dataset=test_dataset, batch_size=conf.batch_size, shuffle=True, num_workers=2, drop_last=False)

    model = BERTClassifier()
    # load pretrained model
    # ckpt = torch.load(pretrain_pos_path)
    #
    # pretrain_params = {}
    # for k,v in ckpt.items():
    #     if 'fc' not in k:
    #         pretrain_params[k] = v
    # #
    # transformer_state_dict = model.state_dict()
    # transformer_state_dict.update(pretrain_params)
    # model.load_state_dict(transformer_state_dict)
    # #model.cuda()
    # model = torch.nn.DataParallel(model.cuda())
    # # 移动到单 GPU
    # # model = model.to(conf.device)

    # 预训练权重路径
    pretrain_pos_path = 'model/pre_train0.pth'

    # 加载预训练权重，排除 'fc' 层
    model = load_pretrained_model(
        model=model,
        checkpoint_path=pretrain_pos_path,
        exclude_layers=['fc']  # 排除所有包含 'fc' 的层
    )

    # 将模型移动到设备
    model = model.to(conf.device)

    num_batch = len(train_dataset) / conf.batch_size
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-05, betas=(0.9, 0.999))

    train(15, training_loader, model)
    validation(testing_loader, model)

